config/routes.rb
Rails.application.routes.draw do
  resources :dogs

end

app/models/dog.rb
class Dog
  include Mongoid::Document
  field :name, type: String
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :image, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image url" %><br>
    <%= f.text_field :remote_image_url%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%=image_tag dog.image, height: "10px" %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @dog.image %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>